### ISSUE TITLE
文章侧栏目录标题点击无效，无法跳转

### ISSUE THREAD

**Issue by mrfengye2021** [bit15k/halo-theme-aircloud#3]
点进文档详情，文章侧栏目录标题点击无效，无法跳转，希望增加一个黑暗切换的功能，超喜欢这个主题，可惜next2.0之后不兼容，希望大佬速速更新!!!!!

**Comment by duaowauigleng** [comment]
一样遇到了这个问题！，求大佬修复bug

**Comment by doraemon-hub-art** [comment]
确实存在这个问题，发现只有纯中文标题可以跳转
